import 'package:flutter/material.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasschoolwidget/generated/GeneratedLogoWidget3.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasschoolwidget/generated/GeneratedButton3Widget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasschoolwidget/generated/GeneratedStatusbarWidget2.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasschoolwidget/generated/GeneratedTeacherprofessoravatarsvgrepocom1Widget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasschoolwidget/generated/GeneratedhomeindicatorblackWidget3.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasschoolwidget/generated/GeneratedStudentpersonpart2svgrepocom1Widget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasschoolwidget/generated/GeneratedWelcomeSchoolWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasschoolwidget/generated/GeneratedButton2Widget1.dart';

/* Frame As School
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAsSchoolWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 83.0,
                              child: GeneratedStatusbarWidget2(),
                            ),
                            Positioned(
                              left: -14.0,
                              top: 890.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 36.0,
                              child: GeneratedhomeindicatorblackWidget3(),
                            ),
                            Positioned(
                              left: 139.0,
                              top: 83.0,
                              right: null,
                              bottom: null,
                              width: 150.0,
                              height: 149.69834899902344,
                              child: GeneratedLogoWidget3(),
                            ),
                            Positioned(
                              left: 53.0,
                              top: 393.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 140.0,
                              child: GeneratedButton2Widget1(),
                            ),
                            Positioned(
                              left: 235.0,
                              top: 393.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 140.0,
                              child: GeneratedButton3Widget(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 411.0,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 85.0,
                              child:
                                  GeneratedStudentpersonpart2svgrepocom1Widget(),
                            ),
                            Positioned(
                              left: 263.0,
                              top: 411.0,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 85.0,
                              child:
                                  GeneratedTeacherprofessoravatarsvgrepocom1Widget(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 297.0,
                              right: null,
                              bottom: null,
                              width: 219.0,
                              height: 35.0,
                              child: GeneratedWelcomeSchoolWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
