import 'package:flutter/material.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedVectorWidget54.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedProfilebuttonsWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedUserprofilecirclesolidsvgrepocom1Widget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedButton4Widget1.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedVectorWidget55.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedButton7Widget1.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedShreyaRajputWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedButton8Widget1.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedhomeindicatorblackWidget5.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedButton3Widget2.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedButton2Widget3.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedStatusbarWidget4.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedSidetaskbarWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedSavedDocumentsWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedButton5Widget1.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedMyCertuficatesWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedWelcomeStudentWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedActiveScholarshipsWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedVectorWidget58.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedstudentprofilewidget/generated/GeneratedActiveParticipationWidget.dart';

/* Frame Student Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStudentProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 890.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 36.0,
                              child: GeneratedhomeindicatorblackWidget5(),
                            ),
                            Positioned(
                              left: 391.0,
                              top: 110.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 19.0,
                              child: GeneratedVectorWidget54(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 64.0,
                              right: null,
                              bottom: null,
                              width: 12.0,
                              height: 18.58457374572754,
                              child: GeneratedVectorWidget55(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 103.0,
                              right: null,
                              bottom: null,
                              width: 230.0,
                              height: 35.0,
                              child: GeneratedWelcomeStudentWidget(),
                            ),
                            Positioned(
                              left: 236.0,
                              top: 225.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 100.0,
                              child: GeneratedButton2Widget3(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 225.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 100.0,
                              child: GeneratedButton7Widget1(),
                            ),
                            Positioned(
                              left: 236.0,
                              top: 424.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 100.0,
                              child: GeneratedButton3Widget2(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 623.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 100.0,
                              child: GeneratedButton5Widget1(),
                            ),
                            Positioned(
                              left: 236.0,
                              top: 623.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 100.0,
                              child: GeneratedButton8Widget1(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 424.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 100.0,
                              child: GeneratedButton4Widget1(),
                            ),
                            Positioned(
                              left: -3.0,
                              top: 41.0,
                              right: null,
                              bottom: null,
                              width: 358.0,
                              height: 851.0,
                              child: GeneratedSidetaskbarWidget(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 119.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 120.0,
                              child:
                                  GeneratedUserprofilecirclesolidsvgrepocom1Widget(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 300.0,
                              right: null,
                              bottom: null,
                              width: 352.0,
                              height: 45.0,
                              child: GeneratedProfilebuttonsWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 345.0,
                              right: null,
                              bottom: null,
                              width: 352.0,
                              height: 45.0,
                              child: GeneratedMyCertuficatesWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 390.0,
                              right: null,
                              bottom: null,
                              width: 352.0,
                              height: 45.0,
                              child: GeneratedActiveScholarshipsWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 435.0,
                              right: null,
                              bottom: null,
                              width: 352.0,
                              height: 45.0,
                              child: GeneratedActiveParticipationWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 480.0,
                              right: null,
                              bottom: null,
                              width: 352.0,
                              height: 45.0,
                              child: GeneratedSavedDocumentsWidget(),
                            ),
                            Positioned(
                              left: -2.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 83.0,
                              child: GeneratedStatusbarWidget4(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 64.0,
                              right: null,
                              bottom: null,
                              width: 12.0,
                              height: 18.58457374572754,
                              child: GeneratedVectorWidget58(),
                            ),
                            Positioned(
                              left: 108.0,
                              top: 243.0,
                              right: null,
                              bottom: null,
                              width: 139.0,
                              height: 28.0,
                              child: GeneratedShreyaRajputWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
