import 'package:flutter/material.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedscreen1widget/generated/GeneratedStatusbarWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedscreen1widget/generated/GeneratedIcons8hide501Widget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedscreen1widget/generated/GeneratedAppleVectorWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedscreen1widget/generated/GeneratedSigninlineWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedscreen1widget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedscreen1widget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedscreen1widget/generated/GeneratedLOGINwithgoogleWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedscreen1widget/generated/GeneratedLogoWidget1.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedscreen1widget/generated/GeneratedLOGINwithappleWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedscreen1widget/generated/GeneratedGoogleVectorWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedscreen1widget/generated/GeneratedLOGINBUTTONWidget1.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedscreen1widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedscreen1widget/generated/GeneratedFORGOTPASSWORDWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedscreen1widget/generated/GeneratedhomeindicatorblackWidget1.dart';

/* Frame Screen 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 930.6983642578125,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 930.6983642578125,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 83.0,
                              child: GeneratedStatusbarWidget(),
                            ),
                            Positioned(
                              left: 139.0,
                              top: 83.0,
                              right: null,
                              bottom: null,
                              width: 150.0,
                              height: 149.69834899902344,
                              child: GeneratedLogoWidget1(),
                            ),
                            Positioned(
                              left: 188.0,
                              top: 262.0,
                              right: null,
                              bottom: null,
                              width: 64.0,
                              height: 25.0,
                              child: GeneratedLoginWidget(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 309.0,
                              right: null,
                              bottom: null,
                              width: 396.0,
                              height: 51.0,
                              child: GeneratedEmailWidget(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 384.0,
                              right: null,
                              bottom: null,
                              width: 396.0,
                              height: 51.0,
                              child: GeneratedPasswordWidget(),
                            ),
                            Positioned(
                              left: 373.0,
                              top: 402.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 26.0,
                              child: GeneratedIcons8hide501Widget(),
                            ),
                            Positioned(
                              left: 300.0,
                              top: 439.0,
                              right: null,
                              bottom: null,
                              width: 98.0,
                              height: 20.0,
                              child: GeneratedFORGOTPASSWORDWidget(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 481.0,
                              right: null,
                              bottom: null,
                              width: 396.0,
                              height: 40.0,
                              child: GeneratedLOGINBUTTONWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 894.6983642578125,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 36.0,
                              child: GeneratedhomeindicatorblackWidget1(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 550.0,
                              right: null,
                              bottom: null,
                              width: 387.0051574707031,
                              height: 36.0,
                              child: GeneratedSigninlineWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 632.0,
                              right: null,
                              bottom: null,
                              width: 396.0,
                              height: 40.0,
                              child: GeneratedLOGINwithgoogleWidget(),
                            ),
                            Positioned(
                              left: 316.0,
                              top: 638.0,
                              right: null,
                              bottom: null,
                              width: 23.828125,
                              height: 24.21875,
                              child: GeneratedGoogleVectorWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 701.0,
                              right: null,
                              bottom: null,
                              width: 396.0,
                              height: 40.0,
                              child: GeneratedLOGINwithappleWidget(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: 706.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 29.750165939331055,
                              child: GeneratedAppleVectorWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
