import 'package:flutter/material.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedframe1widget2/generated/GeneratedSuccess2Widget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedframe1widget2/generated/GeneratedColourWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedframe1widget2/generated/Generated2TextColourWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedframe1widget2/generated/GeneratedHeaderWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedframe1widget2/generated/GeneratedSuccessWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedframe1widget2/generated/Generated1TextColourWidget.dart';

/* Frame Frame 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 696.0,
        height: 415.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 10.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 79.0,
                child: GeneratedSuccessWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 233.0,
                height: 79.0,
                child: GeneratedColourWidget(),
              ),
              Positioned(
                left: 280.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 233.0,
                height: 79.0,
                child: Generated2TextColourWidget(),
              ),
              Positioned(
                left: 280.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 233.0,
                height: 79.0,
                child: Generated1TextColourWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 696.0,
                height: 77.0,
                child: GeneratedHeaderWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 233.0,
                height: 79.0,
                child: GeneratedSuccess2Widget(),
              )
            ]),
      ),
    ));
  }
}
