import 'package:flutter/material.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasstudentwidget/generated/GeneratedWelcomeShreyaWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasstudentwidget/generated/GeneratedButton5Widget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasstudentwidget/generated/GeneratedButton4Widget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasstudentwidget/generated/GeneratedStatusbarWidget3.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasstudentwidget/generated/GeneratedButton7Widget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasstudentwidget/generated/GeneratedVectorWidget53.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasstudentwidget/generated/GeneratedButton2Widget2.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasstudentwidget/generated/GeneratedVectorWidget52.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasstudentwidget/generated/GeneratedhomeindicatorblackWidget4.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasstudentwidget/generated/GeneratedButton3Widget1.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedasstudentwidget/generated/GeneratedButton8Widget.dart';

/* Frame As Student
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAsStudentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 890.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 36.0,
                              child: GeneratedhomeindicatorblackWidget4(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 83.0,
                              child: GeneratedStatusbarWidget3(),
                            ),
                            Positioned(
                              left: 391.0,
                              top: 110.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 19.0,
                              child: GeneratedVectorWidget52(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 64.0,
                              right: null,
                              bottom: null,
                              width: 12.0,
                              height: 18.58457374572754,
                              child: GeneratedVectorWidget53(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 103.0,
                              right: null,
                              bottom: null,
                              width: 219.0,
                              height: 35.0,
                              child: GeneratedWelcomeShreyaWidget(),
                            ),
                            Positioned(
                              left: 236.0,
                              top: 225.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 100.0,
                              child: GeneratedButton2Widget2(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 225.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 100.0,
                              child: GeneratedButton7Widget(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 413.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 100.0,
                              child: GeneratedButton3Widget1(),
                            ),
                            Positioned(
                              left: 236.0,
                              top: 602.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 100.0,
                              child: GeneratedButton5Widget(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 602.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 100.0,
                              child: GeneratedButton8Widget(),
                            ),
                            Positioned(
                              left: 236.0,
                              top: 413.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 100.0,
                              child: GeneratedButton4Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
