import 'package:flutter/material.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedskillcoursewidget/generated/GeneratedJSWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedskillcoursewidget/generated/GeneratedPythonWidget1.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedskillcoursewidget/generated/GeneratedVectorWidget59.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedskillcoursewidget/generated/GeneratedLastseenCoursesWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedskillcoursewidget/generated/GeneratedVectorWidget62.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedskillcoursewidget/generated/GeneratedhomeindicatorblackWidget6.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedskillcoursewidget/generated/GeneratedProfilebuttonsWidget1.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedskillcoursewidget/generated/GeneratedUserprofilecirclesolidsvgrepocom2Widget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedskillcoursewidget/generated/GeneratedRecommededCoursesForYouWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedskillcoursewidget/generated/GeneratedPythonWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedskillcoursewidget/generated/GeneratedStatusbarWidget5.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedskillcoursewidget/generated/GeneratedWDWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedskillcoursewidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedskillcoursewidget/generated/GeneratedNoOngoingCoursesWidget.dart';

/* Frame Skill Course
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSkillCourseWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 890.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 36.0,
                              child: GeneratedhomeindicatorblackWidget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -31.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 419.0,
                              child: GeneratedRectangle5Widget(),
                            ),
                            Positioned(
                              left: 1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 83.0,
                              child: GeneratedStatusbarWidget5(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 64.0,
                              right: null,
                              bottom: null,
                              width: 12.0,
                              height: 18.58457374572754,
                              child: GeneratedVectorWidget59(),
                            ),
                            Positioned(
                              left: 373.0,
                              top: 58.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child:
                                  GeneratedUserprofilecirclesolidsvgrepocom2Widget(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 119.0,
                              right: null,
                              bottom: null,
                              width: 352.0,
                              height: 50.0,
                              child: GeneratedProfilebuttonsWidget1(),
                            ),
                            Positioned(
                              left: 349.0,
                              top: 132.0,
                              right: null,
                              bottom: null,
                              width: 24.998170852661133,
                              height: 25.00244140625,
                              child: GeneratedVectorWidget62(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 187.0,
                              right: null,
                              bottom: null,
                              width: 307.0,
                              height: 28.0,
                              child: GeneratedRecommededCoursesForYouWidget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 249.0,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 85.0,
                              child: GeneratedPythonWidget(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 256.0,
                              right: null,
                              bottom: null,
                              width: 70.83333587646484,
                              height: 99.0,
                              child: GeneratedPythonWidget1(),
                            ),
                            Positioned(
                              left: 306.0,
                              top: 249.0,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 127.0,
                              child: GeneratedJSWidget(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 249.0,
                              right: null,
                              bottom: null,
                              width: 107.0,
                              height: 127.0,
                              child: GeneratedWDWidget(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 406.0,
                              right: null,
                              bottom: null,
                              width: 185.0,
                              height: 28.0,
                              child: GeneratedLastseenCoursesWidget(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 462.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 300.0,
                              child: GeneratedNoOngoingCoursesWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
