import 'package:flutter/material.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedwelcomewidget/generated/GeneratedHomeindicatorwhiteWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedwelcomewidget/generated/GeneratedSTATUSBARWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedwelcomewidget/generated/GeneratedLOGINBUTTONWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedwelcomewidget/generated/GeneratedKushalSchoolWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedwelcomewidget/generated/GeneratedLogoWidget.dart';

/* Frame Welcome
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 944.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 0, 137, 123),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 36.0,
                              child: GeneratedSTATUSBARWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 908.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 36.0,
                              child: GeneratedHomeindicatorwhiteWidget(),
                            ),
                            Positioned(
                              left: 99.0,
                              top: 555.0,
                              right: null,
                              bottom: null,
                              width: 233.0,
                              height: 41.0,
                              child: GeneratedKushalSchoolWidget(),
                            ),
                            Positioned(
                              left: 139.0,
                              top: 388.0,
                              right: null,
                              bottom: null,
                              width: 150.0,
                              height: 149.69834899902344,
                              child: GeneratedLogoWidget(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 803.0,
                              right: null,
                              bottom: null,
                              width: 396.0,
                              height: 50.0,
                              child: GeneratedLOGINBUTTONWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
