import 'package:flutter/material.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedframe2widget1/generated/GeneratedTextWidget4.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedframe2widget1/generated/GeneratedTextWidget6.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedframe2widget1/generated/GeneratedTextWidget8.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedframe2widget1/generated/GeneratedTextWidget9.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedframe2widget1/generated/GeneratedTextWidget2.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedframe2widget1/generated/GeneratedTextWidget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedframe2widget1/generated/GeneratedHeaderWidget1.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedframe2widget1/generated/GeneratedTextWidget7.dart';

/* Frame Frame 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame2Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 696.0,
        height: 415.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 696.0,
                height: 77.0,
                child: GeneratedHeaderWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 33.0,
                child: GeneratedTextWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 19.0,
                child: GeneratedTextWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 26.0,
                child: GeneratedTextWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 26.0,
                child: GeneratedTextWidget6(),
              ),
              Positioned(
                left: 16.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 26.0,
                child: GeneratedTextWidget7(),
              ),
              Positioned(
                left: 16.0,
                top: 173.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 23.0,
                child: GeneratedTextWidget8(),
              ),
              Positioned(
                left: 16.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 21.0,
                child: GeneratedTextWidget9(),
              )
            ]),
      ),
    ));
  }
}
