import 'package:flutter/material.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedyouarewidget/generated/GeneratedStatusbarWidget1.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedyouarewidget/generated/GeneratedIcons8manreadingabook481Widget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedyouarewidget/generated/GeneratedhomeindicatorblackWidget2.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedyouarewidget/generated/GeneratedButton1Widget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedyouarewidget/generated/GeneratedButton2Widget.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedyouarewidget/generated/GeneratedLogoWidget2.dart';
import 'package:flutterapp/kushal_20schoolapp/generatedyouarewidget/generated/GeneratedSchoolsvgrepocom1Widget.dart';

/* Frame You are
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedYouareWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 83.0,
                              child: GeneratedStatusbarWidget1(),
                            ),
                            Positioned(
                              left: -14.0,
                              top: 890.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 36.0,
                              child: GeneratedhomeindicatorblackWidget2(),
                            ),
                            Positioned(
                              left: 139.0,
                              top: 83.0,
                              right: null,
                              bottom: null,
                              width: 150.0,
                              height: 149.69834899902344,
                              child: GeneratedLogoWidget2(),
                            ),
                            Positioned(
                              left: 237.0,
                              top: 393.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 140.0,
                              child: GeneratedButton1Widget(),
                            ),
                            Positioned(
                              left: 53.0,
                              top: 393.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 140.0,
                              child: GeneratedButton2Widget(),
                            ),
                            Positioned(
                              left: 265.0,
                              top: 408.0,
                              right: null,
                              bottom: null,
                              width: 84.0,
                              height: 104.0,
                              child: GeneratedSchoolsvgrepocom1Widget(),
                            ),
                            Positioned(
                              left: 78.0,
                              top: 417.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 88.0,
                              child: GeneratedIcons8manreadingabook481Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
